# 1Password SDK provider: per-vault store (recommended by ESO docs).
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword
  namespace: int-app-gamma
spec:
  provider:
    onepasswordSDK:
      vault: workshop-gamma        # the 1Password vault name
      auth:
        serviceAccountSecretRef:
          name: onepassword-token  # K8s secret we create with the 1Password SA token
          key: token
---
