repos:
  # *** default hooks (core-tasks)
  # https://pre-commit.com/#intro
  # https://github.com/pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # *** extended hooks (language independent-tasks)
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf

  # *** gitleaks implementation
  # https://github.com/gitleaks/gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        entry: gitleaks detect --verbose --redact --source . --config .gitleaks.toml
        pass_filenames: false
