# SecretStore binding ESO to HashiCorp Vault (Dev mode service address, KV v2).
# If you later switch to TLS, change server to https and optionally add caBundle.
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: int-app-beta
spec:
  provider:
    vault:
      server: http://vault.int-vault.svc:8200 # dev-mode Vault service
      path: kv-beta                           # KV mount name
      version: v2                             # KV v2
      auth:
        kubernetes:
          mountPath: kubernetes               # auth method: auth/kubernetes (SA)
          role: eso-beta                      # Vault role you created
          serviceAccountRef:
            name: eso-vault
