apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources live in this namespace
namespace: int-app-beta

resources:
  - 000-preflight.yaml
  - 100-pgsql.yaml
  - 105-secretstore-vault.yaml
  - 110-external-secret.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: beta-stack
      app.kubernetes.io/managed-by: kustomize
