# 1Password SDK provider: per-vault store (recommended by ESO docs).
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword
  namespace: int-app-delta
spec:
  provider:
    onepasswordSDK:
      vault: workshop-gamma        # the 1Password vault name, we'll us the same vault from part-3 (gamma)
      auth:
        serviceAccountSecretRef:
          name: onepassword-token  # K8s secret we create with the 1Password SA token
          key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: int-app-delta
type: Opaque
stringData:
  token: "ops_eyJzaWduSW5BZGRyZXNzIjoibXBvd3ItaXQuMXBhc3N3b3JkLmNvbSIsInVzZXJBdXRoIjp7Im1ldGhvZCI6IlNSUGctNDA5NiIsImFsZyI6IlBCRVMyZy1IUzI1NiIsIml0ZXJhdGlvbnMiOjY1MDAwMCwic2FsdCI6InNsSlhULUk2WUVpRHpPa19CRkZuSlEifSwiZW1haWwiOiJnZmRxaG5pZTVuYmprQDFwYXNzd29yZHNlcnZpY2VhY2NvdW50cy5jb20iLCJzcnBYIjoiYWFiZmVhZTkxYmY1MDE5MmI3NzA2MjRhMmI3Y2VmZGUyM2YxMjQ5Y2FiYjA2ZDc5NGFiZDk0ZTQ4ZjU2MmRhZCIsIm11ayI6eyJhbGciOiJBMjU2R0NNIiwiZXh0Ijp0cnVlLCJrIjoiZXlZTjBNakt1bU95amlMZVhKclNVODk3NzVmNVVyMms5RjlVQmM0T1NMOCIsImtleV9vcHMiOlsiZW5jcnlwdCIsImRlY3J5cHQiXSwia3R5Ijoib2N0Iiwia2lkIjoibXAifSwic2VjcmV0S2V5IjoiQTMtWkNMTlY4LThHU1pZRy1ZSEc4NS1WQkFLOS1ONDMzSi1HRFFFUiIsInRocm90dGxlU2VjcmV0Ijp7InNlZWQiOiIxZjE1NTBkYWNmYjg2MmY1MDQxYTY5YWY0ZmQ4NTg5OTgyNzM1Njc1YWUzMzgxNjJkOTI2Yjk2YmIwODE3MmYzIiwidXVpZCI6IjczUE82TEdKSkJINU5LRkQ1WjY1TVVYVU9JIn0sImRldmljZVV1aWQiOiJnbnhvcGl1ZjZrajZxaGxlaHEyaG9tbXkzNCJ9"
