apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: delta-pg-app-es
  namespace: int-app-delta
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    name: delta-pg-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: '{{ (fromJson .pg_json).username }}'
        password: '{{ (fromJson .pg_json).password }}'
        database: '{{ (fromJson .pg_json).database }}'
        host:     '{{ (fromJson .pg_json).host }}'
        port:     '{{ (fromJson .pg_json).port }}'
        uri:      'postgresql://{{ (fromJson .pg_json).username }}:{{ (fromJson .pg_json).password }}@{{ (fromJson .pg_json).host }}:{{ (fromJson .pg_json).port }}/{{ (fromJson .pg_json).database }}'
        jdbc-uri: 'jdbc:postgresql://{{ (fromJson .pg_json).host }}:{{ (fromJson .pg_json).port }}/{{ (fromJson .pg_json).database }}?user={{ (fromJson .pg_json).username }}&password={{ (fromJson .pg_json).password }}'
  data:
    - secretKey: pg_json
      remoteRef:
        key: "delta-pg-clean/notesPlain"
